apiVersion: apps/v1
kind: Secret
metadata:
  name: firebase-secrets
type: Opaque
stringData:
  FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
  FIREBASE_PRIVATE_KEY: ${FIREBASE_PRIVATE_KEY}
  FIREBASE_CLIENT_EMAIL: ${FIREBASE_CLIENT_EMAIL}
