apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP_NAME
spec:
  selector:
    matchLabels:
      app: $APP_NAME
  template:
    metadata:
      labels:
        app: $APP_NAME
    spec:
      containers:
        - image: aiacevedo/$APP_NAME
          name: $APP_NAME
          env:
            - name: DB_HOST
              value: $APP_NAME-mongodb
            - name: DB_PORT
              value: '27017'
            - name: DB_DATABASE
              value: $APP_NAME
            - name: NODE_ENV
              value: production
          envFrom:
            - secretRef:
                name: firebase-secrets

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP_NAME-mongodb
spec:
  selector:
    matchLabels:
      app: $APP_NAME-mongodb
  template:
    metadata:
      labels:
        app: $APP_NAME-mongodb
    spec:
      containers:
        - image: mongo:6.0.2
          name: mongodb
        - volumeMounts:
            - name: $APP_NAME-db-volume
              mountPath: /data/db
    volumes:
      - name: $APP_NAME-db-volume
        persistentVolumeClaim:
          claimName: $APP_NAME-mongodb-claim

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: $APP_NAME-mongodb-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: $APP_NAME
spec:
  type: ClusterIP
  ports:
    - name: $APP_NAME
      port: 8000
  selector:
    app: $APP_NAME

---
apiVersion: v1
kind: Service
metadata:
  name: $APP_NAME-mongodb
spec:
  type: ClusterIP
  ports:
    - name: $APP_NAME-mongodb
      port: 27017
  selector:
    app: $APP_NAME-mongodb

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: $APP_NAME
  annotations:
    dev.okteto.com/generate-host: $APP_NAME
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: $APP_NAME
                port:
                  number: 8000
            path: /
            pathType: ImplementationSpecific
