name: Deployment CI

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: ${{ github.event.repository.name }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push image to DockerHub
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: aiacevedo/fiuber-trips:latest
      - name: Set APP_NAME
        run: sed -i "s/\$APP_NAME/$(echo ${{ github.event.repository.name }} | tr '[:upper:]' '[:lower:]')/g" ${{ github.event.repository.name }}/kubernetes.yml
      - name: Set FIREBASE_SECRETS_PROJECT_ID
        run: sed -i "s/\$FIREBASE_PROJECT_ID/$(echo ${{ secrets.FIREBASE_PROJECT_ID }} | tr '[:upper:]' '[:lower:]')/g" ${{ github.event.repository.name }}/firebase-secret.yml
      - name: Set FIREBASE_SECRETS_PRIVATE_KEY
        run: sed -i "s/\$FIREBASE_PRIVATE_KEY/$(echo ${{ secrets.FIREBASE_PRIVATE_KEY }} | tr '[:upper:]' '[:lower:]')/g" ${{ github.event.repository.name }}/firebase-secret.yml
      - name: Set FIREBASE_SECRETS_CLIENT_EMAIL
        run: sed -i "s/\$FIREBASE_CLIENT_EMAIL/$(echo ${{ secrets.FIREBASE_CLIENT_EMAIL }} | tr '[:upper:]' '[:lower:]')/g" ${{ github.event.repository.name }}/firebase-secret.yml
      - name: Debug
        run: cat ${{ github.event.repository.name }}/kubernetes.yml
      - name: Delete secrets from okteto
        uses: steebchen/kubectl@v2.0.0
        continue-on-error: true
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: delete -f ${{ github.event.repository.name }}/firebase-secrets.yml
      - name: Apply secrets to okteto
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: apply -f ${{ github.event.repository.name }}/firebase-secrets.yml
      - name: Delete deployment from okteto
        uses: steebchen/kubectl@v2.0.0
        continue-on-error: true
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: delete -f ${{ github.event.repository.name }}/kubernetes.yml
      - name: Apply deployment to okteto
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: apply -f ${{ github.event.repository.name }}/kubernetes.yml
