name: Deployment CI

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Create firebase adminsdk JSON
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "service-account-file.json"
          json: ${{ secrets.SERVICE_ACCOUNT_FILE }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push image to DockerHub
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: aiacevedo/fiuber-trips:latest
      -
        name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: ${{ github.event.repository.name }}
      -
        name: Set APP_NAME
        run: sed -i "s/\$APP_NAME/$(echo ${{ github.event.repository.name }} | tr '[:upper:]' '[:lower:]')/g" ${{ github.event.repository.name }}/kubernetes.yml
      -
        name: Debug
        run: cat ${{ github.event.repository.name }}/kubernetes.yml
      -
        name: Delete deployment from okteto
        uses: steebchen/kubectl@v2.0.0
        continue-on-error: true
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: delete -f ${{ github.event.repository.name }}/kubernetes.yml
      -
        name: Apply deployment to okteto
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: apply -f ${{ github.event.repository.name }}/kubernetes.yml