name: Testing Trip API App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install project dependencies
        run:  yarn install

      - name: Run lint
        run: yarn lint

      - name: Run tests
        run:  yarn test --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with: 
            directory: coverage
